### PR TITLE
Adds values for Account Settings & My Profile

### PR DESCRIPTION
**Pull request by oguzkocer**
It looks like `OPENED_SETTINGS` value is not yet used. To make it clear, I've renamed it to `OPENED_SITE_SETTINGS` which we should start using and added `OPENED_MY_PROFILE` & `OPENED_ACCOUNT_SETTINGS`. These changes are made in consistence with the iOS Repo. [Here is the PR](https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/45) for that change.

/cc @daniloercoli & @astralbodies

### CODE REVIEW

**Comment by oguzkocer** [comment]
I've noticed that it's kind of different to add events to Android. The issues in the original PR should be fixed, but I am still not sure about these changes at all. This is the first time I am adding any events to Android, so please let me know if I messed up anything.

Please note that I've changed the `OPENED_SETTINGS` event values to opened site settings for both Mixpanel and Nosara, so the events will change.

**Comment by daniloercoli** [comment]
Hey @oguzkocer - Could you please checkout wp-android/develop, add the changes available in this PR in a new branch there, and then create a new PR in  wp-android project?

I can do this for you if you're busy.

**Comment by oguzkocer** [comment]
Thanks @daniloercoli. I've [opened the PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3488) in the WordPress-Android project.

**Comment by daniloercoli** [comment]
Addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/3488

**Pull request closed without merging**
